all:	array.h extern.h headfile.h misc.h popuint.h variablf.h chromint.h fuzzyrul.h memberf.h mystring.h ruleset.h vector.h
	gcc -Wall -lm array.cpp average.cpp chromint.cpp fl.cpp flga.cpp fuzzyrul.cpp ga.cpp memberf.cpp mystring.cpp popuint.cpp ruleset.cpp variablf.cpp variance.cpp -o fu_ga_fs

